// Curated starter deck. Every new board begins with these so it's useful on
// first load. Categories drive the colored pill on each card.
//
// SEED_VERSION bumps whenever questions are added below. Existing boards are
// topped up with the new ones on next load (see store.migrate) — matched by
// text, so it never duplicates or resurrects a question you've deleted.
export const SEED_VERSION = 4;

export const SEED_QUESTIONS = [
  { text: "What's the first thing you'd do with a surprise free hour today?", category: 'Icebreaker' },
  { text: 'If your week so far had a soundtrack, what is the opening song?', category: 'Icebreaker' },
  { text: "What's a small win from yesterday that nobody else saw?", category: 'Reflection' },
  { text: "Coffee, tea, or something that really shouldn't count as breakfast?", category: 'Fun' },
  { text: "What's the most useless skill you're secretly proud of?", category: 'Icebreaker' },
  { text: 'If you could instantly master one tool or language, which one?', category: 'Fun' },
  { text: "What's a browser tab you've had open for far too long?", category: 'Fun' },
  { text: "What's the last thing that made you laugh out loud?", category: 'Icebreaker' },
  { text: "If today were a weather forecast for your focus, what's the forecast?", category: 'Icebreaker' },
  { text: 'If you could delete one recurring meeting, which one and why?', category: 'Reflection' },
  { text: 'Spaces or tabs — defend your honor in one sentence.', category: 'This or That' },
  { text: 'If your code had a warning label, what would it say?', category: 'Fun' },
  { text: 'Mountains or ocean for your next time off?', category: 'This or That' },
  { text: 'What fictional character would you want in your standup?', category: 'Fun' },
  { text: 'Pineapple on pizza: feature or bug?', category: 'This or That' },
  { text: "What's your walk-on song if standup had entrances?", category: 'Fun' },
  { text: 'Superpower draft: pause time or rewind ten seconds?', category: 'This or That' },
  { text: 'Who on the team deserves a shout-out today?', category: 'Team' },
  { text: "What's something non-work you're looking forward to this week?", category: 'Team' },
  { text: "What's a hobby you could teach the rest of us in five minutes?", category: 'Team' },
  { text: 'What do you wish people asked you more about?', category: 'Team' },
  { text: 'If the team had a mascot, what should it be?', category: 'Fun' },
  { text: 'Window seat or aisle seat — and what does your answer reveal?', category: 'This or That' },
  { text: 'If you could swap roles with anyone here for a day, who and why?', category: 'Icebreaker' },
  { text: "What's a tiny thing that reliably makes your day better?", category: 'Icebreaker' },
  { text: "What's the best advice you've gotten in the last year?", category: 'Reflection' },
  { text: 'If you had to eat one cuisine for a month, which would it be?', category: 'Fun' },
  { text: "What's one thing you got noticeably better at this month?", category: 'Reflection' },
  { text: "What's the weirdest thing in your fridge right now?", category: 'Fun' },
  { text: 'If you were a command-line tool, what would you do?', category: 'Fun' },
  { text: "What's an app you wish existed but doesn't?", category: 'Fun' },
  { text: "What's your most-used emoji, and what does it really mean?", category: 'Fun' },
  { text: 'What would your work-edition villain origin story be?', category: 'Fun' },
  { text: 'Dark mode or light mode — final answer?', category: 'This or That' },
  { text: 'Early bird or night owl for your best deep work?', category: 'This or That' },
  { text: 'Chat or email for actually getting things done?', category: 'This or That' },
  { text: "What's something a teammate did recently that you appreciated?", category: 'Team' },
  { text: 'What do you want to learn from someone else on this team?', category: 'Team' },
  { text: 'If we celebrated one tiny win right now, what should it be?', category: 'Team' },

  // --- v3: icebreakers -------------------------------------------------
  { text: "What's your go-to karaoke song, even if only hypothetically?", category: 'Icebreaker' },
  { text: "What's the best thing you ate this week?", category: 'Icebreaker' },
  { text: 'Give us a two-word weather report on your energy today.', category: 'Icebreaker' },
  { text: "What's a smell that instantly takes you somewhere else?", category: 'Icebreaker' },
  { text: 'What were you completely obsessed with at age ten?', category: 'Icebreaker' },
  { text: "What's your most controversial breakfast opinion?", category: 'Icebreaker' },
  { text: 'If you had a walk-up sound effect today, what would it be?', category: 'Icebreaker' },
  { text: "What's the last photo you took that you'd happily share?", category: 'Icebreaker' },
  { text: 'You get a free billboard for a week — what goes on it?', category: 'Icebreaker' },
  { text: "What's a word you just enjoy saying out loud?", category: 'Icebreaker' },
  { text: "What's your comfort rewatch — the show or movie you always return to?", category: 'Icebreaker' },
  { text: 'If today had a loading-screen tip, what would yours say?', category: 'Icebreaker' },
  { text: "What's the most spontaneous thing you've done lately?", category: 'Icebreaker' },
  { text: 'Which household chore do you find secretly satisfying?', category: 'Icebreaker' },
  { text: 'Describe your ideal Saturday morning in exactly three words.', category: 'Icebreaker' },
  { text: "What's a sound that instantly relaxes you?", category: 'Icebreaker' },
  { text: 'What did you want to be when you grew up — and how close did you land?', category: 'Icebreaker' },

  // --- v3: reflection ---------------------------------------------------
  { text: "What's a recent mistake that taught you something useful?", category: 'Reflection' },
  { text: 'What are you tolerating right now that you could just fix?', category: 'Reflection' },
  { text: 'What did you do recently that your future self will thank you for?', category: 'Reflection' },
  { text: 'Which of your skills is quietly getting rusty?', category: 'Reflection' },
  { text: 'Which of your habits is doing the most heavy lifting right now?', category: 'Reflection' },
  { text: "What's one thing you understand now that confused you a month ago?", category: 'Reflection' },
  { text: "What's the most valuable five minutes of your day, on average?", category: 'Reflection' },

  // --- v3: fun ------------------------------------------------------------
  { text: 'You must add one absurd rule to standup forever. What is it?', category: 'Fun' },
  { text: 'What would your villain name be if your job title got dramatic?', category: 'Fun' },
  { text: 'Invent a national holiday we clearly need.', category: 'Fun' },
  { text: 'What animal best matches your debugging style?', category: 'Fun' },
  { text: 'You can only communicate in GIFs for a day — thriving or doomed?', category: 'Fun' },
  { text: "What's the most niche rabbit hole you've fallen down online?", category: 'Fun' },
  { text: 'If meetings had theme music, what plays when you join?', category: 'Fun' },
  { text: 'Which snack deserves a promotion?', category: 'Fun' },
  { text: 'Pitch a terrible startup idea in one sentence.', category: 'Fun' },
  { text: 'Pick a completely useless superpower you would still enjoy.', category: 'Fun' },
  { text: 'If your pet — real or imagined — wrote your performance review, what would it say?', category: 'Fun' },
  { text: 'Which movie would be ruined if the characters just communicated clearly?', category: 'Fun' },
  { text: "What's a food combination you swear by that others question?", category: 'Fun' },
  { text: 'Design a merit badge for something you did this week.', category: 'Fun' },
  { text: "What's the best fictional workplace — and would you actually survive there?", category: 'Fun' },
  { text: 'If your commute had a commentator, what would they say about today?', category: 'Fun' },
  { text: 'What flavor is this week? Explain your answer.', category: 'Fun' },

  // --- v3: this or that -----------------------------------------------
  { text: 'Sunrise or sunset — pick your golden hour.', category: 'This or That' },
  { text: 'Booking the trip or planning the trip — which is the fun part?', category: 'This or That' },
  { text: 'Camping: tent, cabin, or hotel with room service?', category: 'This or That' },
  { text: "Standing desk or sitting — where's your spine at today?", category: 'This or That' },
  { text: 'Playlist on shuffle or albums in order?', category: 'This or That' },
  { text: 'Text or call — and does your answer change for bad news?', category: 'This or That' },
  { text: 'Handwritten notes or everything digital?', category: 'This or That' },
  { text: 'Cold pizza for breakfast: yes, or absolutely yes?', category: 'This or That' },
  { text: 'One long vacation or many long weekends?', category: 'This or That' },
  { text: 'Pick your puzzle: jigsaw, crossword, or sudoku?', category: 'This or That' },
  { text: 'Winter person or summer person — no fence-sitting allowed.', category: 'This or That' },
  { text: 'Rewatch an old favorite or always try something new?', category: 'This or That' },
  { text: 'Paper book, e-reader, or audiobook?', category: 'This or That' },

  // --- v3: team -----------------------------------------------------------
  { text: "What's a team tradition we should start?", category: 'Team' },
  { text: 'Who taught you something this week — and what was it?', category: 'Team' },
  { text: "What's the best team you've ever been on, and what made it click?", category: 'Team' },
  { text: 'If we won a team award today, what should it be for?', category: 'Team' },
  { text: 'Describe our team as a band: who plays what?', category: 'Team' },
  { text: 'When has this team surprised you — in a good way?', category: 'Team' },
  { text: "Which teammate's superpower would you borrow this week?", category: 'Team' },
  { text: 'If our team were a heist crew, who does what on the job?', category: 'Team' },
  { text: 'Team road trip: who drives, who DJs, who navigates, who naps?', category: 'Team' },
  { text: 'If this team opened a food truck, what would we sell?', category: 'Team' },

  // --- v3: Michigan --------------------------------------------------------
  { text: 'Pasty with ketchup or gravy — where do you stand?', category: 'Michigan' },
  { text: 'Vernors or Faygo — pick your Michigan pop and defend it.', category: 'Michigan' },
  { text: "What's your favorite Great Lake, and what does that say about you?", category: 'Michigan' },
  { text: 'Troll or Yooper: which side of the Mackinac Bridge suits you best?', category: 'Michigan' },
  { text: "Best coney dog: Detroit style, Flint style, or “what's a coney”?", category: 'Michigan' },
  { text: 'You get one perfect Lake Superior summer day — how do you spend it?', category: 'Michigan' },
  { text: "You're interviewing a euchre partner. What's your one qualifying question?", category: 'Michigan' },
  { text: "What's the most Michigan thing you've ever done?", category: 'Michigan' },
  { text: 'Describe your week as lake-effect snow: light dusting, steady bands, or whiteout?', category: 'Michigan' },
  { text: 'Motown or Motor City techno for your focus playlist?', category: 'Michigan' },
  { text: 'Cherry festival or cider mill season — pick your Michigan harvest.', category: 'Michigan' },
  { text: 'If our team had a Great Lakes freighter, what would we christen it?', category: 'Michigan' },
  { text: 'Petoskey stone hunting: do you have the patience for it?', category: 'Michigan' },
  { text: 'Hold up your hand map: where does your favorite Michigan dot land?', category: 'Michigan' },
  { text: 'Mackinac Island fudge: overrated, underrated, or exactly rated?', category: 'Michigan' },
  { text: 'What would you sculpt for a Winter Carnival snow statue this year?', category: 'Michigan' },
  { text: 'Broomball, curling, or pond hockey — pick your winter league.', category: 'Michigan' },
  { text: 'Sleeping Bear Dunes: worth the climb down, regretted on the way up?', category: 'Michigan' },
  { text: 'First robin or first pothole — the true sign of Michigan spring?', category: 'Michigan' },
  { text: 'Up North: a place or a state of mind? Rule in one sentence.', category: 'Michigan' },
  { text: 'Deer camp, ski hill, or beach town — your Michigan calendar highlight?', category: 'Michigan' },
  { text: 'Tigers, Lions, Red Wings, or Pistons — whose season are you living and dying by?', category: 'Michigan' },
  { text: "What's the farthest you've driven for a good pasty or a better beach?", category: 'Michigan' },
  { text: 'Cider mill order: donuts, cider, both, or "just here for the vibes"?', category: 'Michigan' },
  { text: 'Which Great Lakes lighthouse would you take a remote-work week in?', category: 'Michigan' },
  { text: 'Snow day plan: shovel first, coffee first, or pretend it isn\'t happening?', category: 'Michigan' },

  // --- v3: tech -----------------------------------------------------------
  { text: "What's the oldest piece of tech you still use happily?", category: 'Tech' },
  { text: 'Which tech prediction did you get completely wrong?', category: 'Tech' },
  { text: 'Browser tabs right now: under ten, under fifty, or "tabs are a lifestyle"?', category: 'Tech' },
  { text: "What's a keyboard shortcut that genuinely changed your life?", category: 'Tech' },
  { text: 'AI pair programmer or rubber duck — who gets your hardest bug?', category: 'Tech' },
  { text: 'Which piece of sci-fi tech do you most want to be real?', category: 'Tech' },
  { text: 'What was your first computer, and what do you remember about it?', category: 'Tech' },
  { text: 'Which app would you rebuild from scratch if you had a free month?', category: 'Tech' },
  { text: "What's the best error message you've ever seen?", category: 'Tech' },
  { text: 'Self-driving cars, jetpacks, or teleportation — which ships first?', category: 'Tech' },
  { text: 'What technology will look ridiculous in twenty years?', category: 'Tech' },
  { text: 'Smart home: fully automated, a few gadgets, or light switches forever?', category: 'Tech' },
  { text: "What's the most satisfying sound in computing?", category: 'Tech' },
  { text: 'Vim, Emacs, or "I just want my editor to work"?', category: 'Tech' },
  { text: "What's a piece of “dead” tech you'd bring back?", category: 'Tech' },
  { text: 'Describe your relationship with your notifications in one word.', category: 'Tech' },
  { text: "Give us the one-line version of the hardest bug you've ever tracked down.", category: 'Tech' },
  { text: 'Monorepo or many repos — one sentence, no essays.', category: 'Tech' },
  { text: 'Where does your digital clutter live: downloads folder, desktop, or a folder named "misc"?', category: 'Tech' },
  { text: 'If your codebase were a house, which room needs renovating first?', category: 'Tech' },
  { text: "What's a tool you adopted this year that actually stuck?", category: 'Tech' },
  { text: 'Rate your password hygiene: fortress, fine, or "let\'s not talk about it"?', category: 'Tech' },
  { text: 'Which fictional AI would you trust with production access?', category: 'Tech' },
  { text: 'What tech topic could you give a spontaneous ten-minute talk on?', category: 'Tech' },
  { text: 'Autocomplete, autocorrect, or autoplay — which betrays you most often?', category: 'Tech' },
  { text: "What's the first website you remember visiting?", category: 'Tech' },
  { text: 'Keyboard allegiance: mechanical, laptop chiclet, or ergonomic split?', category: 'Tech' },
  { text: "What's one piece of tech you refuse to upgrade, and why?", category: 'Tech' },
  { text: 'Robot vacuum: pet, appliance, or coworker?', category: 'Tech' },
  { text: 'What would your commit history say about your week so far?', category: 'Tech' },
  { text: 'Dial-up handshake, floppy click, or mechanical keys — the sound of computing history?', category: 'Tech' },

  // --- v4: more fun, less shop talk --------------------------------------
  { text: "What's the worst movie you love without a drop of shame?", category: 'Fun' },
  { text: 'You win a lifetime supply of one thing — what do you pick?', category: 'Fun' },
  { text: "What's your NPC catchphrase — the line you say on loop every week?", category: 'Fun' },
  { text: 'Zombie apocalypse: what role do you fill on the survival team?', category: 'Fun' },
  { text: "What's a hill you'll die on that matters to absolutely no one?", category: 'Fun' },
  { text: 'If animals could talk, which species would be the rudest?', category: 'Fun' },
  { text: "What's your signature dish — or your signature takeout order?", category: 'Fun' },
  { text: 'You get to add one button to the human body. What does it do?', category: 'Fun' },
  { text: 'Which cartoon character are you before your first coffee?', category: 'Fun' },
  { text: "What's the most ridiculous fact you know off the top of your head?", category: 'Fun' },
  { text: 'If your life had a laugh track, when did it go off this week?', category: 'Fun' },
  { text: 'Time machine, one round trip: dinosaurs or ancient Rome?', category: 'Fun' },
  { text: "What's a totally normal thing you're weirdly bad at?", category: 'Fun' },
  { text: "Aliens land and you're the official greeter. What's your opening line?", category: 'Fun' },
  { text: 'Which food would you never share, even with family?', category: 'Fun' },
  { text: "What's your best “sounds fake but is true” story?", category: 'Fun' },
  { text: 'You can make one thing illegal for 24 hours. What is it?', category: 'Fun' },
  { text: 'What would the theme-park ride of your personality be like?', category: 'Fun' },
  { text: 'Which emoji deserves to be retired forever?', category: 'Fun' },
  { text: "What's the pettiest grudge you're still holding?", category: 'Fun' },
  { text: "What's the best gift you've ever received?", category: 'Icebreaker' },
  { text: "What's your unpopular ice-cream opinion?", category: 'Icebreaker' },
  { text: 'Roller coaster or lazy river?', category: 'This or That' },
  { text: 'Karaoke night: grab the mic or hold the camera?', category: 'This or That' },
  { text: "Pancakes or waffles — and no, you can't say both.", category: 'This or That' },
  { text: 'Socks with sandals: crime or cozy?', category: 'This or That' },
  { text: 'Board games or video games?', category: 'This or That' },
  { text: 'Shoes in the house: fine or felony?', category: 'This or That' },
];

export const CATEGORIES = ['Icebreaker', 'Reflection', 'Fun', 'This or That', 'Team', 'Michigan', 'Tech'];

// Questions pulled from the deck in v4 — too much shop talk for a warm-up.
// store.migrate removes these from existing boards (matched by text) so the
// whole deck, not just fresh boards, gets lighter.
export const RETIRED_QUESTIONS = [
  "What's one thing slowing you down that the team could help with?",
  "What did you learn this sprint that you'd tell your past self?",
  "What's a task you keep avoiding — and what's the first 10 minutes of it?",
  'Where did you get unblocked recently, and who helped?',
  "What's one thing we should absolutely keep doing as a team?",
  "What's the smallest change that would make tomorrow run smoother?",
  "What's a definition of “done” you wish we were stricter about?",
  'What would make this sprint a personal success for you?',
  "What's a blocker you can already see coming this week?",
  "What's one process here you'd love to simplify?",
  'What deserves more of your attention this week?',
  'When did you last change your mind about something at work?',
  "What's one thing you'd tell yourself at the start of this quarter?",
  'What part of your work feels effortless lately — and why?',
  "What's a question you've been avoiding asking?",
  'If this sprint had a retro right now, what would your one sticky note say?',
  "What's the kindest piece of feedback you've ever received?",
  'What would "ten percent braver" look like for you today?',
  "What's a boundary that's been working well for you?",
  'What would you do differently if nobody was watching the metrics?',
  "What's one thing that would make our standups better?",
  "What's a skill on this team you'd love a mini-workshop on?",
  "What are you working on that could use a second pair of eyes?",
  "What's the most underrated channel or thread we have?",
  'What should we celebrate before the sprint ends?',
  "What's one piece of context you have that the team might be missing?",
];
